const data={
    hotels:[
        {
            id:1,
            image:"/Images/hotel1.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"newyork",
            price:7255,
            popular:true,
        },
        {
            id:2,
            image:"/Images/hotel2.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Parker Rd.",
            for:"For Rent",
            city:"newyork",
            price:5256,
            popular:false,
        },
        {
            id:3,
            image:"/Images/hotel3.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Poplar Dr.",
            for:"For Sale",
            city:"newyork",
            price:5256,
            popular:true,
        },
        {
            id:4,
            image:"/Images/hotel1.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:5,
            image:"/Images/hotel2.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Parker Rd.",
            for:"For Rent",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:6,
            image:"/Images/hotel3.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:7,
            image:"/Images/hotel4.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Poplar Dr.",
            for:"For Rent",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:8,
            image:"/Images/hotel5.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:9,
            image:"/Images/hotel2.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Poplar Dr.",
            for:"For Rent",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:10,
            image:"/Images/hotel1.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"newyork",
            price:7255,
            popular:true,
        },
        {
            id:11,
            image:"/Images/hotel2.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Rent",
            city:"newyork",
            price:7255,
            popular:false,
        },
        {
            id:12,
            image:"/Images/hotel6.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Poplar Dr.",
            for:"For Rent",
            city:"mumbai",
            price:2400,
            popular:false,
        },
        {
            id:13,
            image:"/Images/hotel4.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"newyork",
            price:1200,
            popular:false,
        },
        {
            id:14,
            image:"/Images/hotel5.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"mumbai",
            price:1040,
            popular:true,
        },
        {
            id:19,
            image:"/Images/hotel5.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"mumbai",
            price:7255,
            popular:false,
        },
        {
            id:20,
            image:"/Images/hotel5.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"mumbai",
            price:300,
            popular:false,
        },
        {
            id:15,
            image:"/Images/hotel6.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Poplar Dr.",
            for:"For Rent",
            city:"paris",
            price:640,
            popular:false,
        },
        {
            id:16,
            image:"/Images/hotel7.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Sale",
            city:"paris",
            price:7255,
            popular:false,
        },
        {
            id:17,
            image:"/Images/hotel8.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Rent",
            city:"paris",
            price:7255,
            popular:false,
        },
        {
            id:18,
            image:"/Images/hotel9.jfif",
            name:"RCE Theaters-907 S Beckford Dr, Henderson, NC 27536",
            address:"8558 Pecan St",
            for:"For Rent",
            city:"london",
            price:7255,
            popular:true,
        },
       
    ]
}
export default data;